#!/bin/sh
. "$(dirname $0)/_/husky.sh"

echo '🏗️👷 Check prettier, lint and types before committing'

yarn lint-staged

# Check tsconfig standards
yarn check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'